from os import environ 

STORAGE_PATH = environ.get('STORAGE_PATH','.')
DATA_PATH = environ.get('DATA_PATH','%s/DATA' % STORAGE_PATH)
ORIGINAL_GENOTYPE_PATH = environ.get('ORIGINAL_GENOTYPE_PATH','%s/GENOTYPES/ORIGINAL' % STORAGE_PATH)
CONVERTED_GENOTYPE_PATH = environ.get('CONVERTED_GENOTYPE_PATH','%s/GENOTYPES/CONVERTED' % STORAGE_PATH)
IMPUTED_GENOTYPE_PATH = environ.get('IMPUTED_GENOTYPE_PATH','%s/GENOTYPES/IMPUTED' % STORAGE_PATH)
OAUTH_CONFIG = environ.get('OAUTH_CONFIG','./oauth.ini')